name: full-workflow

on: [push]

concurrency:
  group: {% raw %} ${{ github.workflow }}-${{ github.ref }} {% endraw %}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: full-workflow
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Run tests
      run: uv run pytest

    - name: Run ruff linting
      run: uv run ruff check

    - name: Run type checks
      run: uv run mypy src